# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginRidRname():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginRidRname(self):
    self.driver.get("http://192.168.0.69/")
    self.driver.set_window_size(1366, 768)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > img").click()
    self.driver.find_element(By.ID, "text_username").click()
    self.driver.find_element(By.ID, "text_username").send_keys("admin")
    self.driver.find_element(By.ID, "text_password").click()
    self.driver.find_element(By.ID, "text_password").send_keys("admin")
    self.driver.find_element(By.ID, "btn_login").click()
    assert self.driver.title == "UWB精确人员定位SDK版"
  
