# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginEidEpwd():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginEidEpwd(self):
    self.driver.get("http://192.168.0.69/")
    self.driver.set_window_size(571, 683)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > img").click()
    self.driver.find_element(By.ID, "btn_login").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".layui-layer-content")
    assert len(elements) > 0
  
