# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest
from HTMLTestRunner import HTMLTestRunner
from models.myunite import MyTest
import sys
sys.path.append("/home/lee/test_projects/henji/pages")
from loginPage import Loginpage

class TestLogin(MyTest):
  '''login模块测试'''

  def test_loginRidRname(self):
    '''正确用户名正确密码'''
    po = Loginpage(self.driver)
    po.user_login(username='admin',password='admin')
    self.driver.implicitly_wait(5)
    po.assert_login_successful()
    time.sleep(2)

  def test_loginRidWpwd(self):
    '''正确用户名错误密码'''   
    po = Loginpage(self.driver)
    po.user_login(username='admin',password='admmin')
    po.assert_login_error()
    time.sleep(2)

  def test_loginWidRpwd(self):
    '''错误用户名正确密码'''    
    po = Loginpage(self.driver)
    po.user_login(username='xxxx',password='admin')
    po.assert_login_error()
    time.sleep(2)

  def test_loginEidRpwd(self):
    '''空id'''    
    po = Loginpage(self.driver)
    po.user_login(username='',password='admin')
    po.assert_login_error()
    time.sleep(2)
  
  def test_loginRidEpwd(self):
    '''空密码'''    
    po = Loginpage(self.driver)
    po.user_login(username='admin',password='')
    po.assert_login_error()
    time.sleep(2)

  def test_loginEidEpwd(self):
    '''空id空密码'''    
    po = Loginpage(self.driver)
    po.user_login(username='',password='')
    po.assert_login_error()
    time.sleep(2)

  def test_data(self):
    po = Loginpage(self.driver)
    login_file = open("/home/lee/test_projects/henji/data/login.txt",'r')
    login_data = login_file.readlines()
    login_data_filename = "/home/lee/test_projects/henji/data/login_result.txt"
    login_result = open(login_data_filename,'w')
    login_result.write("用户名   密码\n")
    for login_data_split in login_data:
        i = login_data_split.split(",",1)
        po.open()
        po.login_username(i[0])
        po.login_password(i[1])
        time.sleep(1)   
        if self.driver.current_url == "http://192.168.0.69/HGMap/example/":
            login_result.write(i[0] + "  " + i[1] + "登陆失败" + "\n")
        elif self.driver.current_url == "http://192.168.0.69/HGMap/example/realTime2D.html":
            login_result.write(i[0] + "  " + i[1] + "登陆成功" + "\n")
            self.driver.back()
        time.sleep(2)
        self.driver.refresh()
        assert self.driver.current_url == "http://192.168.0.69/HGMap/example/realTime2D.html" or "http://192.168.0.69/HGMap/example/"
    login_result.close()
    login_file.close()
    

  def test_url(self):
    '''防止直接输入url跳过登陆界面测试'''
    self.driver.get("http://192.168.0.69/HGMap/example/realTime2D.html")
    time.sleep(2)
    assert self.driver.current_url == "http://192.168.0.69/HGMap/example/index.html"


if __name__ == '__main__':
    #self.driver.get("http://192.168.0.69/").delete_all_cookies()
    testunit = unittest.TestSuite()
    #testunit.addTest(TestLogin("test_url"))    
    #testunit.addTest(TestLogin("test_loginEidEpwd"))
    #testunit.addTest(TestLogin("test_loginRidEpwd"))
    #testunit.addTest(TestLogin("test_loginEidRpwd"))
    #testunit.addTest(TestLogin("test_loginWidRpwd"))
    #testunit.addTest(TestLogin("test_loginRidWpwd"))
    #testunit.addTest(TestLogin("test_loginRidRname"))  
    testunit.addTest(TestLogin("test_data"))  
    now = time.strftime("%Y-%m-%d %H:%M:%S")
    file_name = "../report/report_module/" + now + "login_" + "result.html"
    report_file = open(file_name, 'wb')
    runner = HTMLTestRunner(stream=report_file, title='login模块测试报告', description='用例执行情况:')
    runner.run(testunit)
    report_file.close()